CLIENTVIDEO/CLIENTVIDEO/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CLIENTVIDEO.ServiceReferenceVideo;
using System.IO;
using System.Net;
namespace CLIENTVIDEO.Controllers
{
    public class VideosController : Controller
    {
        SVideoClient dc = new SVideoClient();
        // GET: Videos
        public ActionResult Index()
        {
            Video[] videos = dc.getVideos();
            //Comments[] v=dc.getCommantaires(1);
            return View(videos);
        }

        public ActionResult Create(Video video)
        {
            video = new Video();
           
            return View(video);
        }
        
        [HttpPost]
        public ActionResult Add(Video video=null)
        {
            try
            {
                string sortie = "";
                foreach (string path in Request.Files)
                {

                    HttpPostedFileBase fileUpload = Request.Files[path];
                    if (fileUpload != null && fileUpload.ContentLength > 0)
                    {
                        ISVideo clientUpload = new SVideoClient();
                        FileInfo fileInfo = new FileInfo(fileUpload.FileName);
                        string fileName = Path.GetFileName(Request.Files[path].FileName);
                        int fileLength = Request.Files[path].ContentLength;
                        RemoteFileInfo uploadRequestInfo = new RemoteFileInfo();
                        using (FileStream stream = new FileStream(fileUpload.FileName, FileMode.Open, FileAccess.Read))
                        {
                            uploadRequestInfo.FileName = fileName;
                            uploadRequestInfo.Length = fileLength;
                            uploadRequestInfo.FileByteStream = stream;
                            clientUpload.uploader(uploadRequestInfo);
                            sortie += path + " : "+fileName + "<br/>" ;
                            
                        }
                        if (path == "data") video.data = fileName;
                        else if (path == "poster") video.poster = fileName;
                    }                   
                    
                }
                dc.addVideo(video);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }            
        }

        
        public ActionResult Edit(int? id)
        {
            if (id.HasValue)
            {
                using (SVideoClient v = new SVideoClient())
                {
                    Video video = v.getVideo(id.Value);

                    if (video == null)
                    {
                        return View("Error");
                    }
                    return View(video);
                }
            }
            else
            {
                return View("Error");
            }             
        }

        
        public ActionResult Delete(int? id)
        {
            if (id.HasValue)
            {
                using (SVideoClient v = new SVideoClient())
                {
                    Video video = v.getVideo(id.Value);

                    if (video == null)
                    {
                        return View("Error");
                    }
                    return View(video);
                }
            } 
            else
            {
                return View("Error");
            }             
        }

        // POST: /Videos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id.HasValue)
            {
                using (SVideoClient v = new SVideoClient())
                {
                    Video video = v.getVideo(id.Value);

                    if (video == null)
                    {
                        return View("Error");
                    }
                    dc.deleteVideo(video.code);
                    return RedirectToAction("Index");
                }
            }

            return View("Error");
        }
    }
}

CLIENTVIDEO/CLIENTVIDEO/Views/Videos/Create.cshtml
@model CLIENTVIDEO.ServiceReferenceVideo.Video
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Videos : add";
}

<div class="content">
        <div class="register">
            <div class="col-md-10 login-left">
                @using (Html.BeginForm("Add", "Videos", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.ValidationSummary(true)
                    {
                        <div>
                            <span>Tittle <label>*</label></span>
                            @Html.TextBoxFor(model => model.tittle, new { @id = "tittle", @class = "form-control", placeholder = "Le titre du video" })

                        </div>

                        <div>
                            <span>Genre</span>
                            @Html.TextBoxFor(model => model.category, new { @id = "genre", @class = "form-control", placeholder = "genre de projets" })

                        </div>

                        
                        <div>
                            <span>Describe</span>
                            @Html.TextArea("describe", Model.describe, 6, 60, new { @class = "form-control" })
                        </div>



                        <div>
                            <span>path poster<label>*</label></span>
                            @Html.TextBoxFor(model => model.poster, new { type = "file" })
                        </div>
                        <br/>
                        <div>
                            <span>path video<label>*</label></span>
                            @Html.TextBoxFor(model => model.data, new { type = "file" })
                        </div>
                        <br/>
                        <a class="forgot" href="#">&nbsp;</a>
                        <input type="submit" value="add this movie" />

                    }
                }
            </div>

            <div class="clearfix"> </div>
        </div>
    </div>

CLIENTVIDEO/CLIENTVIDEO/Views/Videos/Delete.cshtml
@model CLIENTVIDEO.ServiceReferenceVideo.Video

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Videos : delete";
}



<div class="content">
    <div class="register">
        <div class="col-md-10 login-left">
            
            @using (Html.BeginForm("DeleteConfirmed/"+@Model.code, "Videos", FormMethod.Post, new { @Model = Model.code, enctype = "multipart/form-data" }))
            {
                @Html.ValidationSummary(true)
                {
                    <div>
                        <span>Tittle <label>*</label></span>
                        @Html.TextBoxFor(model => model.tittle, new { @id = "tittle", @class = "form-control", placeholder = "Le titre du video" })

                    </div>

                    <div>
                        <span>Genre</span>
                        @Html.TextBoxFor(model => model.category, new { @id = "genre", @class = "form-control", placeholder = "genre de projets" })

                    </div>

                    <div>
                        <span>Describe</span>
                        @Html.TextArea("describe", Model.describe, 6, 60, new { @class = "form-control" })
                    </div>



                    <div>
                        <span>path poster<label>*</label></span>
                        @Html.TextBoxFor(model => model.poster, new { type = "file" })
                    </div>
                    <br />
                    <div>
                        <span>path video<label>*</label></span>
                        @Html.TextBoxFor(model => model.data, new { type = "file" })
                    </div>
                    <br />
                    <a class="forgot" href="#">&nbsp;</a>
                    <input type="submit" value="delete this movie" />
                    @Html.ActionLink("Back to list", "Index");
                }
            }
        </div>

        <div class="clearfix"> </div>
    </div>
</div>

CLIENTVIDEO/CLIENTVIDEO/Views/Videos/Edit.cshtml
@model CLIENTVIDEO.ServiceReferenceVideo.Video
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Videos : edit";
}

<div class="content">
    <div class="register">
        <div class="col-md-8 login-left">
            @using (Html.BeginForm("Add", "Videos", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.ValidationSummary(true)
                {
                    <div>
                        <span>Tittle <label>*</label></span>
                        @Html.TextBoxFor(model => model.tittle, new { @id = "tittle", @class = "form-control", placeholder = "Le titre du video" })

                    </div>

                    <div>
                        <span>Genre</span>
                        @Html.TextBoxFor(model => model.category, new { @id = "genre", @class = "form-control", placeholder = "genre de projets" })

                    </div>

                    <div>
                        <span>Describe</span>
                        @Html.TextArea("describe", Model.describe, 6, 60, new { @class = "form-control" })
                    </div>



                    <div>
                            <span>path poster<label>*</label></span>
                            @Html.TextBoxFor(model => model.poster, new { type = "file" })
                        </div>
                        <br/>
                        <div>
                            <span>path video<label>*</label></span>
                            @Html.TextBoxFor(model => model.data, new { type = "file" })
                        </div>
                        <br/>
                        <a class="forgot" href="#">&nbsp;</a>
                        <input type="submit" value="update this movie"/>
                        @Html.ActionLink("Déléte", "Delete");
                        @Html.ActionLink("Back to list", "Index");

                }
            }
        </div>

        <div class="clearfix"> </div>
    </div>
</div>

CLIENTVIDEO/CLIENTVIDEO/Views/Videos/Index.cshtml
@model CLIENTVIDEO.ServiceReferenceVideo.Video[]

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Videos : admin";
}

<div class="content">
    <div class="col-lg-8 col-lg-offset-2 ">
        <div class="alert-info text-center"><h3>Liste des videos</h3></div>
        
            <p>
                @Html.ActionLink("Create New", "Create")
            </p>

        <table class=" table table-hover ">
            <tr>
                <th>Code</th>
                <th>Titre</th>
                <th>Category </th>
                <th>&nbsp; </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.tittle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.category)
                    </td>
                    <td>
                        <a href="@Url.Content("/Videos/Edit/"+@item.code)">Edit</a> |
                        <a href="@Url.Content("/Videos/Delete/"+@item.code)">Delete</a>
                    </td>
                </tr>
            }

        </table>

    </div>
    <div class="clearfix"> </div>
</div>